### ISSUE TITLE
error in deploy button

### ISSUE THREAD

**Issue by iamDonkey** [ton-blockchain/minter#53]
when i click on deploy button i am seeing this error in console.
```
index.js:61 Uncaught (in promise) Error: while converting number to string, invalid number value '1,000', should be a number matching (^-?[0-9.]+).
    at l (index.js:61:13)
    at Object.toWei (index.js:114:15)
    at t.toNano (convert.js:6:20)
    at index.tsx:44:21
    at l (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at S (asyncToGenerator.js:3:20)
    at o (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7d
```

i think problem in input formatting (Number of initial tokens to mint)

**Comment by shaharyakir** [comment]
Fixed with #54. Thanks for reporting!
